### ISSUE TITLE
bindonce.js

### ISSUE THREAD

**Issue by stevermeister** [bahmutov/primes#3]
there is no bindonce.js file in bower anymore, only bindonce.min.js.

so this line in index.html case of fatal error

     <script src="bower_components/angular-bindonce/bindonce.js"></script>

**Comment by bahmutov** [comment]
yeah, I forgot to commit bindonce / update bower.json and could not include this as a commit because the entire history was already pushed to the remote. Could you run 
`bower install angular-bindonce jquery angular-vs-repeat --force` to install it?
